default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: 5
  username: 'hirasawa'
  password: 'hy21261227'

  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: api_test

development:
  <<: *default
  database: api_dev

production:
  <<: *default
  database: api_production
